language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
# command to run tests
script: unittest
env:
  - TEST_SUITE=units
  - TESTFOLDER=TDD/sum
  - TESTFOLDER=TDD/super_sum
